version: "3"
services:
    redis:
        container_name: redis
        image: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - "redis:/data"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'agent-go'
      MYSQL_USER: ahmadirfaan
      #mendefiniskan password user
      MYSQL_PASSWORD: P@ssw0rd
      #password untuk root password
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - mydb:/var/lib/mysql
volumes:
    mydb:
    redis:
